# Generated by Django 2.0.2 on 2019-06-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_indexad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=0, verbose_name='库存量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ship_free',
            field=models.BooleanField(default=True, verbose_name='是否承擔運費'),
        ),
    ]
