# Generated by Django 2.0.2 on 2019-06-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190619_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategory',
            old_name='parent_type',
            new_name='parent_category',
        ),
    ]
