# Generated by Django 2.0.2 on 2019-06-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190616_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='sniger_name',
            new_name='signer_name',
        ),
    ]
