# Generated by Django 2.0.2 on 2019-06-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20190622_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='singer_mobile',
            new_name='signer_mobile',
        ),
    ]
